"Aqui nesse mundinho fechado ela é incrível\n",
"Com seu vestidinho preto indefectível\n",
"Eu detesto o jeito dela, mas pensando bem\n",
"Ela fecha com meus sonhos como ninguém\n",
"Beat it laun, daun daun!\n",
"Beat it, loom, dapn daun\n",
"Beat it laun, baun baun!\n",
"O céu está no chão\n",
"O céu não cai do alto\n",
"É o claro, é a escuridão\n",
"Como eu fiz também\n",
"Só pra poder conhecer\n",
"O que a voz da vida vem dizer\n",
"Enquanto você para e espera\n",
"Eu ando, invado\n",
"Eu abro a porta e entro\n",
"No canto dessa sala emperra\n",
"Eu ligo, acerto\n",
"Eu erro e eu tento\n",
"Bola na trave não altera o placar\n",
"Bola na área sem ninguém pra cabecear\n",
"Bola na rede pra fazer o gol\n",
"Quem não sonhou em ser um jogador de futebol?\n",
"Posso morrer pelo meu time\n",
"Se ele perder, que dor, imenso crime\n",
"Posso chorar se ele não ganhar\n",
"Mas se ele ganha, não adianta\n",
"Não há garganta que não pare de berrar\n",
"Simplesmente posso esperar aqui por você\n",
"Uma eternidade\n",
"Uma tarde inteira\n",
"Tomo um atalho lá só pra te perder\n",
"Enquanto olho os aviões\n",
"Nada tremeu no ar\n",
"Não vi nenhum sinal\n",
"Mesmo assim eu posso esperar\n",
"Estou no meu lugar\n",
"Você já sabe onde é é é\n",
"Não conte o tempo por nós dois\n",
"Pois, a qualquer hora posso estar de volta\n",
"Depois que a noite terminar\n",
"Eu já estou na sua estrada\n",
"Sozinho não enxergo nada\n",
"Mas vou ficar aqui\n",
"Até que o dia amanheça a\n",
"Vou me esquecer de mim\n",
"E você, se puder, não me esqueça!\n",
"Hoje acordei sem lembrar\n",
"Se vivi ou se sonhei\n",
"Você aqui nesse lugar\n",
"Que eu ainda não deixei\n",
"Nem precisei revelar\n",
"Sua foto não tirei\n",
"Como tirei pra dançar\n",
"Alguém que avistei\n",
"E quando eu estiver triste\n",
"Simplesmente me abrace\n",
"E quando eu estiver louco\n",
"Subitamente se afaste\n",
"E quando eu estiver fogo\n",
"Dentro de tudo que cabe em ti\n",
"Mesmo que o mundo acabe enfim\n",
"Dentro de tudo que cabe em ti\n",
"Escorre o tempo que seguro e cabe em minhas mãos\n",
"Eu empresto o meu mundo pra te ter então\n",
"Você vai acreditar talvez\n",
"Ou senão queira partir de vez\n",
"Aquilo que eu sinto por você\n",
"Parece ser maior\n",
"Que o destino que me passa e te passa\n",
"E há de ser um só\n",
"Leva essa canção\n",
"De amor dançante\n",
"Pra você lembrar de mim\n",
"Seu coração lembrar de mim\n",
"Eu preciso de você\n",
"Hoje eu tô jogando tudo fora\n",
"Tudo que não presta mais\n",
"Todo o lixo que juntei\n",
"Nos meus becos e quintais\n",
"Pois é preciso ser honesto\n",
"Se cada dia é diferente\n",
"Sou um anjo e não presto\n",
"Sou só eu no meio desta gente\n",
"Te ver e não te querer\n",
"É improvável, é impossível\n",
"Te ter e ter que esquecer\n",
"É insuportável, é dor incrível\n",
"É como mergulhar no rio\n",
"E não se molhar\n",
"É como não morrer de frio\n",
"No gelo polar\n",
"Funk lá no morro da Mangueira\n",
"Essa menina tá dizendo sim, eu sei\n",
"Noite bamba, tudo à beça\n",
"Baião na rampa do Cruzeiro\n",
"Seu nome é Jackie, Jackie Tequila\n",
"Seu nome é Jacqueline Misty iê iô Tequila\n",
"Reggae lá na rádio do Café\n",
"Rapaziada que estiver afim vai lá\n",
"Eu vou ficar com Jackie\n",
"Se é que Jackie vai pra lá\n",
"Eu sinto sua falta\n",
"Não posso esperar tanto tempo assim\n",
"O nosso amor é novo\n",
"É o velho amor ainda e sempre\n",
"Que culpa a gente tem de ser feliz?\n",
"Que culpa a gente tem, meu bem?\n",
"O mundo bem diante do nariz\n",
"Feliz aqui e não além\n",
"Tem um lugar diferente\n",
"Lá depois da saideira\n",
"Quem é de beijo, beija\n",
"Quem é de luta, capoeira\n",
"Oh! Comandante, capitão\n",
"Tio, brother, camarada\n",
"Chefia, amigão\n",
"Desce mais uma rodada\n",
"Desce mais\n",
"Bem mais que o tempo\n",
"Que nós perdemos\n",
"Ficou pra trás\n",
"Também o que nos juntou\n",
"Desfaz o vento\n",
"O que há por dentro\n",
"Desse lugar\n",
"Que ninguém mais pisou\n",
"Coveiros gemem tristes ais\n",
"E realejos ancestrais juram que\n",
"Eu não devia mais querer você\n",
"Os sinos e os clarins rachados\n",
"Zombando tão desafinados\n",
"Querem, eu sei, mas é pecado\n",
"Eu te perder\n",
"Políticos embriagados\n",
"Dançando em guetos arruinados\n",
"E os profetas desacordados\n",
"A te ouvir\n",
"Eu sei que eles vem tomar\n",
"Meu drinque em meu copo a trincar\n",
"E me pedir pra te deixar partir\n",
"Vamos fugir deste lugar, baby!\n",
"Vamos fugir\n",
"Tô cansado de esperar\n",
"Que você me carregue\n",
"Pois diga que irá\n",
"Irajá, Irajá\n",
"Pra onde eu só veja você\n",
"Você veja a mim só\n",
"Marajó, Marajó\n",
"Qualquer outro lugar comum\n",
"Outro lugar qualquer\n",
"Guaporé, Guaporé\n",
"Qualquer outro lugar ao sol\n",
"Outro lugar ao sul\n",
"Céu azul, Céu azul\n",
"Onde haja só meu corpo nu\n",
"Junto ao seu corpo nu\n",
"Uuh, uuh, uuh\n",
"Uuh, uuh, uuh\n",
"Uuh, uuh, uuh\n",
"Tão fácil perceber\n",
"Que a sorte escolheu você\n",
"E você, cego, nem nota\n",
"Quando tudo ainda é nada\n",
"Quando o dia é madrugada\n",
"Você gastou sua cota\n",
"Misterioso luar de fronteira\n",
"Derramando no espinhaço quase um mar\n",
"Clareando a aduana\n",
"Venezuela, donde estás?\n",
"Não sei por que nessas esquinas vejo o seu olhar\n",
"Não sei por que nessas esquinas vejo o seu olhar\n",
"Espalhe por aí boatos de que eu ficarei aqui\n",
"Espalhe por aí boatos de que eu ficarei aqui\n"