"Então, então, então sai, sai, sai da minha frente\n",
"Sai, sai, sai da minha frente\n",
"Hoje eu vou dar trabalho numa onda diferente\n",
"Hoje eu vou dar trabalho numa onda diferente\n",
"Eu quero ver você dançar\n",
"Eu quero ver você dançar\n",
"Simplesmente eu sei que tudo que foi\n",
"Importante pra mim\n",
"Da minha vida se foi\n",
"Então me fez ser assim\n",
"Dentro dessa armadura, nessa vida dura\n",
"Não sou Indiana Jones\n",
"Então, sem aventura\n",
"Uh, uh, uh, uh, uh\n",
"Uh, uh, uh, uh, uh\n",
"Uh, uh, uh, uh, uh\n",
"Yo te quiero ver enloquecer\n",
"Quiero provocarte y yo sé que\n",
"Tú no lo admites, pero puedo ver\n",
"Muérete de ganas, quieres verme hacer\n",
"Essa mina é louca\n",
"Quando eu tô bolado, ela quer beijo na boca\n",
"Se eu tô com frio, ela tira a minha roupa\n",
"Louca, essa mina é louca\n",
"En su cuerpo puedo ver la definición\n",
"Se ve que lo trabaja, eres motivación\n",
"Le pedí que me ayude con una misión\n",
"Que me llene entera de satisfacción\n",
"Cuida el terreno\n",
"No sabes en lo que te estás metiéndo\n",
"Una vez que tú siembres en otro suelo\n",
"E olha como ela chegou, de um jeito doce\n",
"Anitta, sabe, eu te quero, não é de hoje\n",
"Então vem jogando, rebolando, oh, sua malandra\n",
"Que a nossa noite termina na sua cama\n",
"Se não tá mais à vontade, sai por onde entrei\n",
"Quando começo a dançar, eu te enlouqueço, eu sei\n",
"Meu exército é pesado, e a gente tem poder\n",
"Ameaça coisas do tipo: Você!\n",
"Vai!\n",
"A mí me gusta\n",
"Every time you look at me that way\n",
"A mí me gusta\n",
"All the dirty things you need every day\n",
"Vela, vela, vela cuando empieza el show\n",
"Prende los motores, tres, dos, uno, go!\n",
"Ella se rebela porque tiene flow\n",
"Toda la favela bailando el dembow\n",
"Pensou que eu fosse cair mesmo nesse papo?\n",
"Que tá solteiro e agora quer parar\n",
"Eu finjo, vou fazendo meu teatro\n",
"E te faço de palhaço, pra te dominar\n",
"Tá pedindo, an, an\n",
"Se prepara, vou dançar, presta atenção\n",
"An, an tutudum an, an\n",
"Cê aguenta an, an\n",
"Se eu te olhar\n",
"Descer, quicar até o chão\n",
"Aposto contigo, vai fazer o que eu quiser\n",
"Com essa turbulência, tu não vai parar em pé\n",
"Hoje eu fico louca, looping de beijar na boca\n",
"Vem comigo quem aguenta essa porra a noite toda\n",
"Agora vai começar o combatchy\n",
"Quica, quica, bate, bate\n",
"Hoje vai rolar um fight de bumbum\n",
"Aqui não vai ter empate\n",
"O bagulho é de verdade\n",
"Meu popô vai dar nocaute em qualquer um\n"
