"Como se me conhecesse ela me contou\n",
"Seu passado de aventuras\n",
"Onde ela passou\n",
"E eu sem nem um preconceito\n",
"Com amor lhe aceitei, um mês e pouco mais tarde\n",
"Com ela me casei\n",
"Fui seresteiro das noites\n",
"Cantei vendo o alvorecer\n",
"Molhado com os pingos da chuva\n",
"Com flores pra lhe oferecer)\n",
"Nosso senhor para sempre te levou\n",
"Nem ao menos me deixou o fruto do nosso amor\n",
"Aquele filho seria a nossa alegria\n",
"Eu senti naquele dia ser um pai, ser o Senhor\n",
"Num encontro casual\n",
"Você perguntou as horas\n",
"Meio sem jeito no olhar\n",
"A Lua descia do céu\n",
"Eu cantando você acordava\n",
"Com os olhos cheios de amor\n",
"Abria a janela e me beijava\n",
"Depois de te dar uma flor\n",
"Quase chorando eu ia embora\n",
"Ah! Se voltasse esse tempo\n",
"De poesia sem dor de outrora\n",
"Algo além da paixão\n",
"Um amor surreal\n",
"Me manchou de batom, era tudo de bom\n",
"Nunca vi nada igual\n",
"Como posso me acostumar?\n",
"Te ver com um novo amor\n",
"Sei que quando vai dormir, abraçando outro corpo\n",
"Em vão tentar esquecer\n",
"Nossos beijos, nossas bocas murmurando no silêncio\n",
"Isso é o que me faz sofrer\n",
"Com esse olhar meigo\n",
"Me fez nascer no peito\n",
"Esta paixão\n",
"Nosso senhor, para sempre te levou\n",
"Nem ao menos me deixou, o fruto do nosso amor\n",
"Aquele filho, seria nossa alegria\n",
"Eu senti naquele dia, ser um pai, ser um senhor\n",
"E depois na sua sala ao lado\n",
"Atende o telefone e anota os recados\n",
"E coloca sobre minha mesa\n",
"Se ela ligar outra vez\n",
"Pode dizer que eu saí\n",
"Mas se ela insistir e voltar a ligar\n",
"Pode dizer que eu morri\n",
"Mas se ela insistir e voltar a ligar\n",
"Pode dizer que eu morri\n",
"O seu beijo me enlouquece e me faz estremecer\n",
"O seu corpo junto ao meu me leva às nuvens de prazer\n",
"Amo você\n",
"Não deu certo uma vez\n",
"E nunca mais vai dar\n",
"Depois do que me fez\n",
"Não era pra eu te amar\n",
"Eu tive um amor\n",
"Amor tão bonito\n",
"Daqueles que matam\n",
"Com sabor de saudade\n",
"Meu ex-amor\n",
"Tem coisas que a gente não esquece\n",
"Mas você não merece\n",
"Tanta dor\n",
"Foi bonito demais\n",
"Mas eu estou sozinho\n",
"Foi rico de amor\n",
"E hoje estou tão só\n",
"Pra que tentar fugir de mim?\n",
"Se eu sempre vou seguir\n",
"Na tua direção\n",
"Pra que tentar me esquecer?\n",
"Pra mim só tem você\n",
"E o resto é solidão\n",
"Espero, uma chance sua\n",
"Nesta noite de Lua\n",
"Ter você aqui\n",
"E hoje já estou crescido\n",
"Sou o seu marido, és minha mulher\n",
"Acabou-se a alegria\n",
"Brigar todo dia é o que você quer\n"
